### ISSUE TITLE
Setup instruction is needed

### ISSUE THREAD

**Issue by and7ey** [TECH7Fox/sipclient-hass-integration#3]
I tried to setup the client, but Config Flow doesn't work - 
`Config flow could not be loaded: {"message":"Invalid handler specified"}`

What should be the configuration.yaml data? Some example would be helpful.

**Comment by and7ey** [comment]
Below is the error message:

```
2024-10-01 09:57:50.917 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.sipclient.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/sipclient/__init__.py", line 11, in <module>
    from .sip_to_webrtc import incoming_call, setup_event_listeners
  File "/config/custom_components/sipclient/sip_to_webrtc.py", line 6, in <module>
    from aiortc import (
  File "/usr/local/lib/python3.12/site-packages/aiortc/__init__.py", line 22, in <module>
    from .rtcpeerconnection import RTCPeerConnection
  File "/usr/local/lib/python3.12/site-packages/aiortc/rtcpeerconnection.py", line 10, in <module>
    from .codecs import CODECS, HEADER_EXTENSIONS, is_rtx
  File "/usr/local/lib/python3.12/site-packages/aiortc/codecs/__init__.py", line 13, in <module>
    from .g711 import PcmaDecoder, PcmaEncoder, PcmuDecoder, PcmuEncoder
  File "/usr/local/lib/python3.12/site-packages/aiortc/codecs/g711.py", line 5, in <module>
    from av.audio.codeccontext import AudioCodecContext
  File "av/audio/codeccontext.pyx", line 1, in init av.audio.codeccontext
ValueError: av.stream.Stream size changed, may indicate binary incompatibility. Expected 72 from C header, got 56 from PyObject
```
